packages:
  - .

allowBuilds:
  electron-winstaller: true
  esbuild: true
  vue-demi: true

confirmModulesPurge: false

ignoredBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - vue-demi
